### ISSUE TITLE
Virus don't use fuck this guy.

### ISSUE THREAD

**Issue by RoToolsnScripts** [HectorsGrav3/Discord-Account-Generator#1]
Do not join it, there is a base64encoded code in the code. Please do not use this: the b64 decoded code is here:

this guy is the retard of retards the dumbass of dumbasses.

![image](https://user-images.githubusercontent.com/111227293/189537783-c90856bf-9d03-4043-bbce-3d5a10d88f01.png)

**Comment by HectorsGrav3** [comment]
Would've told you what it is but you are toos tupid to understand :skull:
